/*
 * grafos.java
 *
 * 
 */
import java.awt.*;

/**
 *
 * @author  MARY
 */
public class grafos extends javax.swing.JFrame {
    
    pincel  lienzo;
    
    
    /** Creates new form grafos */
    public grafos() {
        initComponents();
        
        lienzo = new pincel(this);
        lienzo.setBackground(new java.awt.Color(236, 233, 216));
        getContentPane().add(lienzo);
        lienzo.setBounds(60,20,400,300);
        
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        caja1 = new javax.swing.JTextField();
        cajax = new javax.swing.JTextField();
        cajay = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(60, 360, 90, 23);

        getContentPane().add(caja1);
        caja1.setBounds(200, 360, 110, 20);

        getContentPane().add(cajax);
        cajax.setBounds(360, 360, 80, 20);

        getContentPane().add(cajay);
        cajay.setBounds(460, 360, 80, 20);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PX");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 340, 50, 14);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PY");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 340, 40, 14);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-587)/2, (screenSize.height-449)/2, 587, 449);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int vt = Integer.parseInt(caja1.getText());
        int vx = Integer.parseInt(cajax.getText());
        int vy = Integer.parseInt(cajay.getText());
        
        this.lienzo.asignacion(vx,vy,vt);
        
        this.lienzo.repaint();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grafos().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caja1;
    private javax.swing.JTextField cajax;
    private javax.swing.JTextField cajay;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    
}
